### ISSUE TITLE
Implement MOTION_BLOCKING heightmap.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#104]
If I'm not mistaken, rain uses this heightmap to determine when it should stop falling. Once weather is implemented, the heightmap can be properly tested.

- [x] #105

**Comment by dyc3** [comment]
According to this: https://minecraft.fandom.com/wiki/Chunk_format

> MOTION_BLOCKING: The highest block that blocks motion or contains a fluid.

**Comment by tim-kt** [comment]
Implemented by #523, can be closed.
