### ISSUE TITLE
Access to custom values in player's game profile

### ISSUE THREAD

**Issue by LooFifteen** [valence-rs/valence#179]
It would be wonderful if it were possible to access every value in the game profile provided by Mojang/Velocity, so that custom values can be passed to the sub-server without the need for an external messenger.

**Comment by rj00a** [comment]
Just curious, what are you using the custom values for?

**Comment by SLLCoding** [comment]
Passing some data from the proxy like the player's internal profile ID, that can be used to get values from a microservice, for example.
