### ISSUE TITLE
The `Text` struct is too large.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#18]
`cargo clippy` often complains that `std::mem::size_of::<Text>()` is too large. There are a few things that could be done.
- Stop using `Cow<'static, str>` everywhere and just use `String`. We can reintroduce it later if it turns out to be important.
- Get rid of the `Option<bool>`s by manually implementing `Serialize` and `Deserialize`. Use a bitfield struct with two bits per `Option<bool>`.

**Comment by dyc3** [comment]
I'd like to take a stab at this.
