### ISSUE TITLE
Some text content types are not yet implemented.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#19]
https://minecraft.fandom.com/wiki/Raw_JSON_text_format

In the `text` module, plain text is implemented but the other content types are missing/need work.
- translated text
- scoreboard values
- entity names
- keybind
- NBT values

**Comment by gabrielztk** [comment]
Can I try my hand at this issue?

**Comment by dyc3** [comment]
Absolutely! Looking forward to your PR
