### ISSUE TITLE
Valence Website

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#2]
I don't have any webdev experience. Also, I have the valence.rs domain name.

Edit: Here's what I would expect the website to have once finished:
- Dedicated page for documentation with a tutorial-like guide (markdown).
- FAQ page.
- A clean landing page with the Valence logo and links to github, discord, crates.io, etc. It should have a short summary of Valence's goals and capabilities.
- A page for announcing releases including patch notes (markdown).
- Minimal design. Nothing too flashy.
- Uses the `valence.rs` domain name.
- Available in a `website` directory at the root of the Valence repository. If it would make more sense to be in a separate repo we could discuss that.
- Hosted on GitHub for easy edits?

# Sources of Inspiration
- Minestom: https://minestom.net/
  I quite like the simplicity of the landing page. I'm indifferent about the use of gitbook for the docs.
- Feather: https://feathermc.org/
  This one is a bit bare-bones but it's worth mentioning.
- Rocket: https://rocket.rs/
  Not Minecraft related, but It's got all the ingredients for a good site.

**Comment by UltimateDoge5** [comment]
Hi,
This project is something that I have been actually thinking about but I don't have enough rust expeirience.
I still would like to contribute to this project and since I'm a web dev I could help with this.

You got any particular ideas on your mind?

**Comment by williamdes** [comment]
We could make a Hugo website?

Also your bio website seems down

Can you apply for GitHub sponsors so I can sponsor you?

Also, would you mind creating a valence github organization and moving the project into it?
It would avoid some bus factor we can observe in the rust ecosystem :)

**Comment by UltimateDoge5** [comment]
Yea, I was thinking about using hugo or astro. And making an organisation seems a good idea too.

**Comment by williamdes** [comment]
> Yea, I was thinking about using hugo or astro.

You can copy paste everything from my website: https://github.com/wdes/website 

> And making an organisation seems a good idea too.

Yayy

One question, it's not clear why you say it's a framework but in fact you have a runnable server. How is this all built together?

**Comment by UltimateDoge5** [comment]
You could say that the word framework in web dev is really stretched. With astro you can make a mostly static site and sprinkle js components wherever you want. This results in low bundle sizes and quick load times.

It supports markdown and MDX. You can even use other frameworks like react and vue.

**Comment by williamdes** [comment]
> You could say that the word framework in web dev is really stretched.

Indeed, this is why I think it will confuse some people browsing this Rust project

**Comment by UltimateDoge5** [comment]
It is in reality a rust implementation of a java minectaft server with easy "plugin" expansion in mind but it does sound quite long.

On a hero section it would be quite akward.

**Comment by rj00a** [comment]
> Also, would you mind creating a valence github organization and moving the project into it? It would avoid some bus factor we can observe in the rust ecosystem :)

Thanks for the suggestion. I've done this now.

I will also move the `serde_nbt` crate to a separate project under the organization.

> Can you apply for GitHub sponsors so I can sponsor you?

I will be applying to GitHub sponsors shortly ❤️

> Also your bio website seems down

Yeah, it's a placeholder for now. (no webdev experience and all that)

**Comment by UltimateDoge5** [comment]
Alright,
we need a repo for the web site, it doesn't need to be public but can, that is not a problem.

We need to choose the framework for it. 
Do you plan any dynamic content on the site or only static?

**Comment by williamdes** [comment]
> Alright, we need a repo for the web site, it doesn't need to be public but can, that is not a problem.
> 
> We need to choose the framework for it. Do you plan any dynamic content on the site or only static?

To use GitHub pages without paying it will need to be public. Static would be a good idea because of how easy the setup will be : basically a CNAME to GitHub.

**Comment by UltimateDoge5** [comment]
I mean a free hosting in 2022 is not a problem. We can use vercel/netlify or github pages as you said.
I would use astro as its great at static content and gives us some flexability in the future if we want to do something dynamic/use state frameworks.

**Comment by LeoDog896** [comment]
@UltimateDoge5 and @williamdes, since we've mainly setttled on a framework choice, do y'all want to continue the development details on Valence's discord?

**Comment by UltimateDoge5** [comment]
If you would give me an invite link that would be awesome!

**Comment by williamdes** [comment]
> @UltimateDoge5 and @williamdes, since we've mainly setttled on a framework choice, do y'all want to continue the development details on Valence's discord?

Sure, let's continue to discuss on Discord. URL ?

**Comment by LeoDog896** [comment]
For anyone else, it's on the README: https://discord.gg/8Fqqy9XrYb

**Comment by RihanArfan** [comment]
I think VitePress would be great for the site as it'd make writing docs dirt easy. https://vitepress.vuejs.org/

**Comment by UltimateDoge5** [comment]
Idk, SPA for docs doesn't connect for me. And as I can see its still in alpha. Does it even support SEO?

**Comment by RihanArfan** [comment]
> Idk, SPA for docs doesn't connect for me. And as I can see its still in alpha. Does it even support SEO?

from https://vitepress.vuejs.org/guide/getting-started:
> VitePress is currently in alpha status. It is already suitable for out-of-the-box documentation use, but the config and theming API may still change between minor releases.

It's still an SSG so SEO will be great, and it's very lightweight so web vitals score highly. But mainly good DX so writing docs won't be a pain because of framework/tooling.

**Comment by cloudybyte** [comment]
> I think VitePress would be great for the site as it'd make writing docs dirt easy. https://vitepress.vuejs.org/

If we're talking purely about docs, [docusaurus](https://github.com/facebook/docusaurus) might be worth taking a look at. 
It basically takes markdown such as [this](https://github.com/azuma-chat/azuma-chat.github.io/tree/main/docs) and turns them into a static page like [this](https://azuma-chat.github.io/). (Notice: This is my own project. I really don't want to self-ad, but its the best demo I had on hand)

**Comment by XBagon** [comment]
had a crazy thought.. could make the "website" a valence minecraft server with all the information provided in creative ways in-game. and for a plus have the "real" website run have a wasm compatible minecraft client connected to the server :P

**Comment by williamdes** [comment]
> had a crazy thought.. could make the "website" a valence minecraft server with all the information provided in creative ways in-game. and for a plus have the "real" website run have a wasm compatible minecraft client connected to the server :P (more on the marketing side ofc :D docs would probably best in the old fashined way upside_down_face)

That's brilliant!

**Comment by FussballAndy** [comment]
> had a crazy thought.. could make the "website" a valence minecraft server with all the information provided in creative ways in-game. and for a plus have the "real" website run have a wasm compatible minecraft client connected to the server :P (more on the marketing side ofc :D docs would probably best in the old fashined way 🙃)

While I like the idea I feel like it would kinda make accessibility or finding certain pieces of information pretty hard, it would probably give me this vibe of custom scrolling effects. Additionally I think it could kind of fail to show why you should even pick Valence over the default mc server (or bukkit, spigot etc.) which is especially performance. You probably wouldn't be able to simulate like 1000 cows with wasm in your browser especially since hardware acceleration is off by default iirc.

**Comment by FussballAndy** [comment]
> And hardware acceleration being disabled by default for wgpu stuff would be new to me?

That was rather a hard guess sorry for that. Though it would seem a bit weird to me that browsers would allow gpu usage although hardware accel is disabled as the reason people disable it is exactly to not have their gpu used, but again I am not sure how it actually handles it 😅

**Comment by cloudybyte** [comment]
As the gameclient website would be a showoff addition anyway, moving forward with a hugo website (or sth like that) would be the way to go). We could even only build a docs site for now.

**Comment by kubo6472** [comment]
Hey @rj00a let me know if this would be somewhat usable: https://valence-docs.netlify.app/
source: https://github.com/kubo6472/valence-docs

**Comment by rj00a** [comment]
@kubo6472 Hey, thanks for working on this! It looks nice. I've updated this issue with some of my expectations. Let me know what you think.

The website you made in its current state would need some adjustments before I'd be willing to accept it. In particular, the Valence logo repeated three times doesn't look so great. I also think a dark theme by default would look nice. It would need to work well with the logo. Perhaps the banner at the top could be lighter so the logo in the top left doesn't blend in? Just throwing out some ideas.

Can the site be adjusted to have a FAQ page and release notes page as described above?

**Comment by kubo6472** [comment]
@rj00a let me know if it looks more okay. I went for some placeholder content. I think it is perfectly possible to host in from a directory and deploy from gh actions (if there's some problem with netlify). All custom content apart from the homepage is 100% markdown, so I think you should be able to work with it, and replace it for something real yourself. Let me know how should I structure the repo for a PR, then. Thanks

**Comment by rj00a** [comment]
@kubo6472 Thanks. You can go ahead and make a PR that adds a `website` directory at the root of the repo. It should include a README.md describing the steps needed to use it (which commands necessary, etc).

We can make the website live once Valence 0.2.0 is around the corner.

**Comment by kubo6472** [comment]
Okay, sure

**Comment by Snowiiii** [comment]
If you need help to Code a Site i can help

**Comment by kubo6472** [comment]
> If you need help to Code a Site i can help

#138 feel free to submit PRs to my branch :)
