### ISSUE TITLE
Is there a way to set the block type of a `FallingBlock` entity?

### ISSUE THREAD

**Issue by mymatsubara** [valence-rs/valence#203]
I'm trying to change the block type of a `FallingBlock` entity, but I couldn't find a way to do it :cry:.
Does anybody know how to can I do it? If it is not supported atm, I can give a try implementing it!

Btw, thank you very much for working on valence! I'm having a lot of fun using it! Keep on the great work.

**Comment by dyc3** [comment]
I don't think it's possible at the moment. See the TODO in entity.rs. If you do want to contribute it, please target the `ecs_rewrite` branch, and make your changes in the `valence_new` crate.

**Comment by mymatsubara** [comment]
Thank you very much for the informations! When I get some free time, I'll try to contribute it!
