### ISSUE TITLE
Calculate Client Ping

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#207]
There should be a~~n optional~~ component for `Client` that is able to keep track of the client's current ping. If the component is present, it should be used to display the client's current ping in the tab list via one of the systems in `PlayerList::default_system_set`.

I'm assuming the `Ping` and `Pong` packets can be used for this, but wiki.vg claims that the vanilla server does not use this.

**Comment by rileysu** [comment]
I assume this could also be implemented using `KeepAlive` packets? It might be better since these are already required.

**Comment by rj00a** [comment]
Ah, of course. That makes more sense.
