### ISSUE TITLE
Create fake client(s) for testing purposes similar to `rust-mc-bot`.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#211]
[rust-mc-bot](https://github.com/Eoghanmc22/rust-mc-bot) is a tool I've been using to stress test the server. It would be nice if we had our own version of it so we don't have to work with a tool in a separate git repo.

Ideally our version will behave very similarly. It will be built on top of `valence_protocol`.

**Comment by qualterz** [comment]
Is this a proposal about a separate library within the framework that enables instantiation of in-memory clients and do client-side actions on a server programmatically? Potentially, such a library could be used to develop pseudo-players to build, for example, PvE servers.

**Comment by dyc3** [comment]
@qualterz That's already possible IIRC. You spawn in entities and add the McEntity component to them with the player EntityKind. This is talking about using bot clients that connect via the network to stress test how valence handles it.

We could just include `rust-mc-bot` as a git submodule, that would probably be easiest. Another option would be to do this with the unit testing infra we set up, but that might not yield totally accurate results.
