### ISSUE TITLE
Getting io.netty.handler.codec.DecoderException error when joining particles example

### ISSUE THREAD

**Issue by wjwzpeajhc** [valence-rs/valence#267]
### Valence  Version
cc2571d
### Current Behavior

When I try to join [particles](https://github.com/valence-rs/valence/blob/main/crates/valence/examples/particles.rs) example using Vanilla 1.19.3 client I get following error:
```
Internal Exception: io.netty.handler.codec.DecoderException: LongArray with size 96 is bigger than allowed 5
```

### Expected Behavior

I was expecting not to get the error and just join the server successfully

### Steps To Reproduce

1. clone repository using `git clone https://github.com/valence-rs/valence`
2. run example using `cargo r -r --example particles`
3. join localhost using Vanilla Minecraft 1.19.3 client

### Checklist

- [X] I have searched the issues of this repo and believe that this is not a duplicate.
- [x] This used to work before.

**Comment by dyc3** [comment]
Confirmed, I'm able to reproduce this.

**Comment by AviiNL** [comment]
With the packet inspector, I'm seeing that the packet id for `ParticleS2c` in valence is 0x23, while on wiki.vg particles are defined with packet id [0x22](https://wiki.vg/Protocol#:~:text=Displays%20the%20named%20particle) where 0x23 is `Update Light`
