### ISSUE TITLE
Inventory Packet Validation

### ISSUE THREAD

**Issue by dyc3** [valence-rs/valence#292]
## Describe the problem related to your feature request.

At the moment, we trust the client a little too much when it comes to modifying inventories. For example, a client can send a click slot packet that just adds any item to any slot out of thin air.

## What solution would you like?

There are 2 types of assertions we need to make on incoming modifications:
1. plain invalid info that shouldn't be processed ever
2. making sure items aren't being duplicated/spawned/deleted, aka conservation of mass

Type 1 validations:
- [x] slot ids are in-bounds
- [x] item stack amounts are in-bounds
- [ ] ~~some slots are "outbound only" eg. crafting result slots~~ decided not to do this because it's not that useful and pretty hard to assert for

Type 2 validations:
- [x] while the cursor is holding an item
    - [x] and clicking an empty slot, the item should go into the clicked slot
    - [x] and clicking a filled slot, 
        - [x] if the item is the same type, and same nbt data, an amount in the cursor item's stack be transferred to the slot's stack such that the resulting slot's stack reaches 64 (maybe make this configurable? some items can only stack to 1)
        - [x] otherwise, the slot and cursor item should swap
    - [x] and the user clicks and drags, the resulting differences in item stacks should add up to the correct amount
        - example: user is holding 5 diamonds, slot 1 is holding 1 diamond, slot 2 is empty. user clicks and drags the 5 item stack across slot 1 and 2. now the user should be holding 1 diamond, slot 1 should have 3 diamonds, slot 2 should have 2 diamonds
- [x] while the cursor is **not** holding an item
    - [x] and clicking an empty slot, nothing should happen
    - [x] and clicking a filled slot
       - [x] and pressing shift, using left click, the slot's stack should go directly to another slot (it doesn't matter which one)
       - [x] using right click, half the stack should be picked up (which slot gets the remainder if the amount in the stack is an odd number)
       - [x] otherwise, the slot's stack should be transferred to the cursor

The type 2 validations may be expensive, so ideally we should allow the user to disable it.

There's probably some more that I missed, but that should be enough to catch most cases.

## What alternative(s) have you considered?

We could also not do this, and defer this to end users, but I think that could end up being pretty error prone.

## Additional context

For #288 

https://wiki.vg/Protocol#Click_Container

**Comment by rj00a** [comment]
> ~~some slots are "outbound only" eg. crafting result slots~~ decided not to do this because it's not that useful and pretty hard to assert for

- What happens if an item is moved to the outbound slot and it gets overwritten by the result of a crafting recipe? (Does the client predict crafting recipe results? Not really sure how that all works).
- Being able to move items to the output of, say, a furnace seems like a potential source of bugs for future code that updates furnaces.
- Clients effectively have an extra inventory slot.

Seems like something we should address at some point.
