### ISSUE TITLE
Panic when dropping item from inventory while chest is open

### ISSUE THREAD

**Issue by dyc3** [valence-rs/valence#295]
## Valence Version

c9fbd1a24e86e6df4698640ef08ae59303ab728a

## What You Did

1. Run `cargo run --example chest`
2. give yourself any item and place it on hotbar
3. open the chest
4. mouse over the item in your hotbar
5. press drop key
6. crash and burn

<details>

<summary>Playground</summary>

```rust
PASTE YOUR PLAYGROUND CODE HERE
```

</details>

## What Went Wrong

The server should not panic.

## Additional Information

Caused by this line:

https://github.com/valence-rs/valence/blob/c9fbd1a24e86e6df4698640ef08ae59303ab728a/crates/valence/src/client/event.rs#L865

because it fails to consider that an inventory might be open, so slot ids for the player inventories may be different

**Comment by SeseMueller** [comment]
I tested it too, it starts panicking at slot number 46. 
The player has 36 Inventory slots, four armor slots, one offhand slot, four crafting slots and one crafting result slot, making it 46 slots. 
It seems that your suspicion was right, the server acts as if only the player's inventory is open.
I'll look into it.
