### ISSUE TITLE
Packet inspector: Arrow keys are not functioning correctly.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#297]
## Valence Version

c9fbd1a24e86e6df4698640ef08ae59303ab728a

## What You Did

Clicked on a packet from the list on the left and used the arrow keys.

## What Went Wrong

Does not immediately go to the next or previous packet. It appears to deselect on the first input, then select the next packet on the next input.

**Comment by AviiNL** [comment]
Maybe an OS specific issue? On windows I am unable to reproduce this. If no packet is selected, the up arrow should select the very first packet, on down arrow the second one. When a packet is selected, up and down works as intended.
