### ISSUE TITLE
How should Valence be versioned?

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#3]
I don't believe the Valence API will ever be in a stable state if we assume the following:

1. We only target the most recent version of MC.
2. Updating to a new version of MC is a breaking change.
3. New MC versions can be released at any time and cause anything to break.

With that in mind, it might be better to just start at version 1.0.0 instead of releasing 0.x.y versions as is usually done in the Rust ecosystem.

For the initial Valence release, I'll just release it as `0.1.0+mc1.19.2` to be safe.

(The `+mc1.19.2` bit at the end there is "build metadata" which is ignored for the purpose of version ordering. It's useful to know what MC version is being targeted.)

**Comment by williamdes** [comment]
The bit at the end is a great idea!

**Comment by Kevin-Konradi** [comment]
I think this is a great consideration.
But personally I would release 1.0.0 when you think the project is in a more-or-less stable state

**Comment by rj00a** [comment]
Lets keep releasing 0.x.y versions until the only thing that would break us is MC updates.
