### ISSUE TITLE
Inventory Items as Entities

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#319]
## Describe the problem related to your feature request.

The current inventory API has a couple problems (among others):
1. Using `ItemStack` directly is not very pleasant. It's fine when the type and count of items need to be accessed, but working with enchantments, lore, and other metadata requires interfacing with the loosely-typed NBT compound.
2. It's difficult to associate custom data with items because `Option<ItemStack>` is not open for extension. The data must be stored outside the inventory. This is important for UI elements and other things with unique behaviors.

## What solution would you like?

Make every item an entity in the ECS. We could have the following components on items, with some being optional:
- `InventoryRef(Entity)`
    A pointer back to the inventory this item is a part of. Needed so that update systems know what inventory to mark changes in.
- `Slot(u16)`
    The slot index of the item. Needed so that update systems know what slot to mark as modified (we could replace this with a linear search for this item's `Entity` in the inventory?).
- `Count(u8)`
- `ItemKind`
- `Nbt(Compound)`
    Typically modified indirectly through `Damage`, `Enchantment`, `Lore`, etc. but also left exposed as an escape hatch. (TODO: store this in binary form for faster transmission?)
- `Damage`
- `Enchantment`
- `Lore`

Then, the `Inventory` slot array would be a `Box<[Option<Entity>]>`. We rely on change detection in the components to send changes to clients.

### Challenges
- How do we ensure that invariants are not broken accidentally when moving and deleting items? Bevy currently lacks "archetype invariants" and "relations" so this is very difficult to enforce.

    One possibility is to require all slot changes to be made through `Command`s. This way, changes are performed atomically when the system buffers are applied. Another option is to require use of a helper type containing the inventory and query of items.

## What alternative(s) have you considered?

We could keep things as they are and work to make `ItemStack` more convenient by adding various helper methods.

But continuing the trend of making everything an entity ~~(like chunks and block entities)~~ would be more consistent.

## Additional context

Part of #257. May also help with #307.

**Comment by dyc3** [comment]
How do we make sure users can't create >1 item stacks for the same slot?

**Comment by rj00a** [comment]
Closing for the reasons mentioned in #257.
