### ISSUE TITLE
Panic on build script when using sqlx in combination with valence

### ISSUE THREAD

**Issue by lukashermansson** [valence-rs/valence#324]
## Valence Version
Commit:
abf90649017ef4037f7cb75c4d6c9679042ffc40

## What You Did

I added the crate "sqlx" version 0.6.3 (and same with 0.7.0-alpha.2) to the list of my dependencies and recompiled

## What Went Wrong

I would expect for valence to still compile.

instead I got this compilation error:
 `thread 'main' panicked at '"_Entity.allay.ambientWithItem" is not a valid Ident' `

## Additional Information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- theories about what might be going wrong
The crate heck is used in valence without any features enabled, and in sqlx with unicode feature enabled) these should behave additively https://doc.rust-lang.org/cargo/reference/features.html?highlight=additive#feature-unification but appears to have different behavior depending on the enabled feature 
- links to related bugs, PRs or discussions
I isolated the issue to happen in a common library (Thanks to Moulberry and AviiNL)
link to issue I opened in the affected crate:
https://github.com/withoutboats/heck/issues/42
(this crate looks to not be actively maintained anymore, maybe look for an alternative)

- workarounds that you used
AviiNL tried this to get it to compile 
![image](https://user-images.githubusercontent.com/7715996/234657596-e87d3670-afe2-4861-bb2b-2fc4fdce7708.png)

- screenshots
Cutout from some messages in the discord
![image](https://user-images.githubusercontent.com/7715996/234657083-1100e0ef-e087-496c-91dd-8a0aebd6f118.png)

- logs

**Comment by lukashermansson** [comment]
Yea sorry, turns out shift+enter posted this prematurely, I edited the issue with more information, sorry for the inconvenience

**Comment by lukashermansson** [comment]
Update on this,
According to the downstream crate maintainer the behavior we are relying on for this is the correct behavior for the crate.

so it turns out the crate is not behaving correctly with the "unicode" feature enabled. 
Unfortunately I will not be submitting a pr to this downstream crate as I feel I lack the understanding required to implement a good fix, so feel free to make a contribution there if you want to.

We could go ahead with the workaround tested by AviiNL in the wait for a fix, or some other smarter solution, any suggestions?

**Comment by rj00a** [comment]
Thanks for investigating. Link to issue: https://github.com/withoutboats/heck/issues/42

I'm in favor of `.replace(".", "_")` as a workaround until the issue is fixed downstream.
