### ISSUE TITLE
Boss Bar API

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#337]
## Describe the problem related to your feature request.

There is no API for [boss bars](https://minecraft.fandom.com/wiki/Commands/bossbar).

## What solution would you like?

Create a new crate called `valence_boss_bar`. Every boss bar is an entity with the following components:
- `BossBarTitle`
- `BossBarHealth`
- `BossBarStyle` (contains color and division)
- `BossBarFlags`
- `Uuid` (defined in `valence_entity` currently)
- `BossBarViewers`. Contains the set of client entities viewing this boss bar. When the boss bar is despawned with the `Despawned` component, the boss bar is removed from all viewers.

Change detection on the components is used to send packets to the boss bar viewers.

Also might be good to use another component containing a `Vec<u8>` to cache boss bar packets before sending them to viewers.

## What alternative(s) have you considered?

When entity relations in `bevy_ecs` become a thing, the `BossBarViewers` component could probably be replaced with a `boss bar -> client` relation for each viewer.

## Additional context

See the `BossBarS2c` packet.

**Comment by tarunsamanta2k20** [comment]
@rj00a I am interested to work on this issue. But I need some help.

**Comment by dyc3** [comment]
Here some some references/pointers to get you started:

- The relevant packet is documented here: https://wiki.vg/Protocol#Boss_Bar
- The packet is already defined here: https://github.com/valence-rs/valence/blob/main/crates/valence_core/src/packet/s2c/play/boss_bar.rs

All you need to do is make the components and implement the systems to actually send the packets, preferably with unit tests.

**Comment by JackCrumpLeys** [comment]
This should be closed.
