### ISSUE TITLE
Remove the prelude

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#353]
## Describe the problem related to your feature request.

The valence prelude (`valence::prelude`) currently contains a bunch of random items. There's no real procedure for deciding if something belongs in or out of the prelude, as I've just been adding things in there as I needed them in the examples. This creates confusion for end users, and means there's more than one way to do things (you can decide to import something through the prelude or not).

## What solution would you like?

Remove it and update the examples. It's better to be explicit.

Problem: the `bevy_ecs` module is in the prelude, and that's necessary to use the Bevy ECS macros without them failing. To fix this, re-export `bevy_ecs` at the root of `valence` and add a doc comment explaining this.

## What alternative(s) have you considered?

- Keep the prelude and decide precisely what things belong in or out.
- Add per-crate or per-module preludes and either keep or remove the main prelude.

**Comment by rj00a** [comment]
The main issue I see here is that the examples become very verbose. This is made worse by the fact that rust-analyzer insists on importing things through the crates in `crates/` instead of the main `valence` crate. At this time, I would prefer to continue maintaining the prelude.

**Comment by UStuej** [comment]
@rj00a Do you want `valence::prelude` removed completely?

**Comment by rj00a** [comment]
@UStuej The current plan is to keep the prelude.
