### ISSUE TITLE
Per clients entity

### ISSUE THREAD

**Issue by Bafbi** [valence-rs/valence#360]
## Describe the problem related to your feature request.

Sometime, you need to have entities that can only be seen by only one or a group of players.

## What solution would you like?

A composant that reference the group of client that the packet will be send to.
If the composant is not present, the entity is normally process.

## What alternative(s) have you considered?

Maybe dispawn the entity if all client are disconnected

**Comment by dyc3** [comment]
Is this a duplicate of #342?

**Comment by Bafbi** [comment]
Yea it basically is
