### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#39]
Valence should have support for [bungeecord](https://github.com/SpigotMC/BungeeCord) and [velocity](https://velocitypowered.com/) proxies. I think something like this could work in `Config`.

```rust
#[non_exhaustive]
#[derive(Copy, Clone, Eq, PartialEq, Default)]
pub enum ConnectionMode {
    #[default]
    Online,
    Offline,
    Bungeecord,
    Velocity,
}
```

(Looks like velocity does not support 1.19 currently? What should we do if Valence is updated before the proxies are?)

**Comment by alice39** [comment]
How should proxies be supported?
I was thinking something similar to `spigot.yml -> bungeecord: true/false` option does or is it more than that? Because I might give this a try

**Comment by rj00a** [comment]
My idea is that you would have `fn connection_mode(...) -> ConnectionMode` instead of `fn online_mode(...) -> bool` in the `Config`.
