### ISSUE TITLE
Crashes in the `particles` example

### ISSUE THREAD

**Issue by Hugo4IT** [valence-rs/valence#393]
## Valence Version

[0f3e6f2](https://github.com/valence-rs/valence/commit/0f3e6f2b7f0ace1f0a11ef9f5d908c9ddc2bbcf5)

## What You Did

Cloned the repo, ran the `particles` example and joined with vanilla 1.20.1 Minecraft.

## What Went Wrong

It should of course cycle through all the particles and it does that fine but the problem is that two of the 95 particle types crash the client with the error:

```
Connection Lost

Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException: readerIndex(47) + length(4)
exceeds writerIndex(47): PooledUnsafeDirectByteBuf(ridx: 47, widx: 47, cap: 47)
```

## Additional Information

I ran the example with Nightly as the crate wouldn't compile at all in stable mode since the update to bevy 0.11

The crashes only occur on the particles `Particle::LandingCherryLeaves` (31) and `Particle::ElectricSpark` (93). I tried looking into the packet encoding but the packets seem to correctly match the one described on [wiki.vg](https://wiki.vg/Protocol#Particle)

<img width="849" alt="image" src="https://github.com/valence-rs/valence/assets/48245742/cef5b4c7-c5b0-4286-b9df-c25f22608ea5">

The logs don't show anything useful either, the server doesn't print anything at all and the client only prints the usual stuff:

```log
[10:22:23] [Render thread/INFO]: Connecting to 127.0.0.1, 25565
[10:22:30] [Render thread/INFO]: Started 2 worker threads
[10:22:30] [Render thread/INFO]: Loaded 0 advancements
[10:22:40] [Render thread/INFO]: Stopping worker threads
```

**Comment by LeoDog896** [comment]
I can triage this as well. Most likely, it's outdated wiki.vg documentation - ill look into this.
