### ISSUE TITLE
Make the packet inspector work when encryption is enabled.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#404]
## Describe the problem related to your feature request.

Right now the packet inspector doesn't function correctly when encryption is enabled. It will occasionally display "unknown packet" and stop functioning.

## What solution would you like?

I believe the inspector could intercept the server's request to enable encryption during the handshake process. It could encrypt and decrypt packets as they're sent to/from the server while sending and receiving unencrypted packets to/from the client. The server thinks it's talking to an encrypted client, while the client thinks it's talking to an unencrypted server.

This would save us a lot of headache when testing the examples, since users wouldn't need to modify the `ConnectionMode` to start using the inspector.

## What alternative(s) have you considered?

At the very least it should detect that encryption is enabled and display an error.

**Comment by natanalt** [comment]
While it's possible to intercept encryption requests and have the inspector handle them on the client's behalf, I don't think it's easily possible to enable full online mode support. Online mode requires interaction with Mojang session servers, and without the client's access token the inspector can't fully authenticate the player.

Similar programs like https://github.com/Heath123/pakkit specifically ask the user to log into their Microsoft account when inspecting an online server, probably to get an access token. I'm not sure if implementing someone like this here would be worth the effort

Maybe there's some other way of doing it, I couldn't think of one :p

**Comment by rj00a** [comment]
Right, the access token. Clearly I did not think this through 🤦

I agree that it's probably not worth the effort right now. I'll leave this issue open until the packet inspector properly displays an error.
