### ISSUE TITLE
Redesign Text API

### ISSUE THREAD

**Issue by PonasKovas** [valence-rs/valence#411]
Mentioned on #288 .

I noticed that `reset` value is not representable by `Color`. 

Also partially related - webcolors in `Text` are only supported since 1.16, so I think we should fallback to the legacy colors for server list pings before 1.16.

I would like to work on this, so I want to know if you had anything more in mind. What else needs to be improved with the Text API?

**Comment by rj00a** [comment]
A few issues that come to mind:
- Can't pattern match on a `Text` object or inspect its structure. `TextContent` and `TextInner` are private. 
- Can't mutate a `Text` object in place through a `&mut`. Methods on the `TextFormat` trait take `self` by value. Convenient for building a new object from scratch, but maybe not flexible enough.
- The `Into<Text>` pattern is convenient for function arguments, but it requires that an owned `Text` be passed in, even though most of the time the function only needs a `&Text`. We might need a dedicated trait for this.
- There's been some discussion about a domain specific language for `Text`, but I don't know what that would be or if it's really needed.
- Need to cross reference with Spigot and Minestom to see if we're missing anything.
- Some `From` impls for `Text` might be missing.

**Comment by rj00a** [comment]
[azalea-chat](https://github.com/mat-1/azalea/tree/main/azalea-chat) for reference.

**Comment by PonasKovas** [comment]
I personally don't think we need a DSL here, the `TextFormat` trait does it's job completely fine.

What do you think about just using `Into<Cow<'a, Text>>` instead of `Into<Text>`?

**Comment by rj00a** [comment]
That seems like a good idea 👍
