### ISSUE TITLE
Update `aes` and `cfb8` dependencies

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#42]
`aes` and `cfb8` crates are at `0.8` currently but they are `0.7` in Valence. I tried updating a while back but couldn't figure out how to use the new API (It's very different).

Not much urgency on this one.

**Comment by dyc3** [comment]
It turns out there are some breaking changes here. I'll throw up a draft PR of what I have so far.

**Comment by dyc3** [comment]
I think the best way to upgrade this is to create a couple of new types that implement `AsyncRead` and `AsyncWrite` that can encrypt and decrypt blocks on demand. That way, we can use [`decrypt_block_mut()`](https://docs.rs/cfb8/latest/cfb8/struct.Decryptor.html#method.decrypt_block_mut) which doesn't consume the cipher. I'm not familiar enough with async rust to be able to do this myself.

**Comment by rj00a** [comment]
Neither am I.
