### ISSUE TITLE
Publish nightly docs

### ISSUE THREAD

**Issue by hwittenborn** [valence-rs/valence#423]
It doesn't look like there's docs for the current version on `main`, but I think they'd be quite helpful for anyone who has valence as a Git dependency from this repository. Things like `DefaultPlugins` don't show up on docs.rs (I'm assuming because they weren't present in the 0.1 release), but it'd be nice to figure out what those do without digging into the actual source code.

**Comment by hwittenborn** [comment]
I forgot I could just run `cargo doc` locally to get the needed documentation, that's a suitable solution for me. I don't know if y'all want to get something online for this going though, so I'll leave this open until y'all think it's appropriate to close.

**Comment by rj00a** [comment]
Docs sourced from the `main` branch available on the future `valence.rs` website would be nice. Let's leave this open until that's implemented.

**Comment by hwittenborn** [comment]
Is there anything major stopping this from happening @rj00a? I imagine you could just throw the docs up on GitHub actions fairly trivially, but I'm not sure if there's anything else blocking it.

If it's just a matter of it not being implemented yet I'd be more than glad to make a PR.

**Comment by rj00a** [comment]
The main issue is that the website doesn't exist yet. See #382.

Also I just realized "Use CI to automatically generate API reference" is one of the tasks there.

**Comment by hwittenborn** [comment]
API docs could get done outside of that PR though, right @rj00a? I could throw up a PR real quick if you'd be fine getting that out of the way.

**Comment by rj00a** [comment]
Sure, let's do that.
