### ISSUE TITLE
Are the packet buffers big enough?

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#43]
in `Config` there are the functions `incoming_packet_capacity` and `outgoing_packet_capacity`. They control the maximum size of the buffers used to hold packets to prevent unbounded memory usage. They reach their maximum when the server is sending packets faster than the client can receive it or vice versa.

Are the default values large enough? I recall stackotter saying he was kicked from `terrain.rs` with a render distance of 32 because of this. Is this even the right approach to the problem?

**Comment by Demozo** [comment]
Just playing around with the examples. Can confirm that a render distance of 32 got me kicked.

**Comment by jivvy** [comment]
2000 cows on the cow sphere example gets you kicked
