### ISSUE TITLE
Make "text viewer" the default tab in the packet inspector.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#452]
## Describe the problem related to your feature request.

Clicking on a packet in the packet inspector shows the "hex viewer" by default. However, the "text viewer" is usually what you want.

## What solution would you like?

Make the text viewer tab the default. It should also be placed left of the hex viewer.

**Comment by ShivangRawat30** [comment]
Hey I am currently learning rust, as it is a good first issue can you please assign this to me.
