### ISSUE TITLE
Custom skins for NPC Player entities

### ISSUE THREAD

**Issue by dyc3** [valence-rs/valence#460]
## Describe the problem related to your feature request.

It's common to have custom NPCs on minigame servers with custom skins.

## What solution would you like?

There should be an optional component that you can attach to a Player entity to change it's texture.

## What alternative(s) have you considered?

None

## Additional context

Apparently, this is possible in Bukkit by setting the `textures` property on `GameProfile`. I haven't found a good specific code example yet other than [this forum post](https://www.spigotmc.org/threads/set-custom-skins-to-players.431292/?__cf_chl_tk=Xzmp8JTDE3xb6jHwSa4bNShwT3BX.kEKTlC2BVIH90s-1691589807-0-gaNycGzNC-U).

**Comment by dyc3** [comment]
A new example would be good, unless we can work it into another large example similar to `parkour` or `ctf`.

**Comment by Bafbi** [comment]
I'm not really fond of having examples for literally every little thing, I think we can just demonstrate it on an existing example that uses an entity and we could having a mapping of certain feature to certain example if someone search something

**Comment by dyc3** [comment]
He's talking about this component: https://github.com/valence-rs/valence/blob/f8a01b4c7b91120c9ae206d7074f47c9873e0d60/crates/valence_client/src/lib.rs#L494-L506

**Comment by dyc3** [comment]
I was able to get a custom skin on a player entity, but it's unclear to me where the signature comes from, and whether or not it's required.

In the base64, there's a field called `signatureRequired` that would imply you could make it optional.

```
{
  "timestamp" : 1691706573156,
  "profileId" : "e88274eb3f514d60bc1ad95481218303",
  "profileName" : "AnimalTheGamer",
  "signatureRequired" : true,
  "textures" : {
    "SKIN" : {
      "url" : "http://textures.minecraft.net/texture/1de2c83f8f4fb38069f55f52e4f8ee5f0867229ead91b7e79def754b70ea9433",
      "metadata" : {
        "model" : "slim"
      }
    }
  }
}
```

**Comment by Bafbi** [comment]
@dyc3 https://wiki.vg/Mojang_API#UUID_to_Profile_and_Skin.2FCape
