### ISSUE TITLE
Block entities

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#5]
Support for [block entities](https://minecraft.fandom.com/wiki/Block_entity) should be added to the chunk API.

It looks like there are only a few things that need explicit support from Valence.
* The text on signs
* Banner patterns
* The entity inside of spawners
* Player data in player heads
* Maybe some other blocks?

My current idea is to put a `HashMap<u32, BlockEntity>` in each chunk. The key is the block index and the value is an `enum` of the possible block states.

**Comment by Kevin-Konradi** [comment]
Shouldn't the Block Entities be stored for each Chunk section?

**Comment by Kevin-Konradi** [comment]
I'm gonna try to work on this one
