### ISSUE TITLE
Make the packet inspector only depend on `valence_protocol`.

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#502]
## Describe the problem related to your feature request.

The packet inspector depends on the `valence` crate, but it only needs the things from `valence_protocol`.

## What solution would you like?

Remove the dependency on `valence` and depend on `valence_protocol` directly. Then, regenerate the file in `assets/depgraph.svg`.

## Additional context

There was a time when `valence_protocol` didn't exist, so the the current situation was necessary.

**Comment by natanalt** [comment]
I could take care of it once #501 goes through
