### ISSUE TITLE
Replace `for item in query` with `query.for_each`

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#528]
## Describe the problem related to your feature request.

[`Query::for_each`](https://docs.rs/bevy_ecs/latest/bevy_ecs/system/struct.Query.html#method.for_each) is known to be significantly faster than [`Query::iter`](https://docs.rs/bevy_ecs/latest/bevy_ecs/system/struct.Query.html#method.iter) due to rustc failing to optimize properly.

## What solution would you like?

Replace all uses of `.iter()/.iter_mut()/&/&mut` with `.for_each/.for_each_mut` where feasible.

## What alternative(s) have you considered?

Don't do this since it could be considered a temporary rustc failure that will be fixed in the future. (But when will it be fixed?)

## Additional context

Not sure if there's an open bevy issue for this.

**Comment by rj00a** [comment]
https://github.com/rust-lang/rust/issues/104914

> Yes, that's a long-known issue (see the blog post linked previously) but there aren't any good plans how to fix it.

**Comment by rj00a** [comment]
https://github.com/bevyengine/bevy/pull/6773 plans to deprecate `Query::for_each`.

**Comment by Milo123459** [comment]
as bevy is planning to deprecate it, should we not just leave it as is as it is an upstream issue.

**Comment by rj00a** [comment]
Yeah, I would rather not make any changes until https://github.com/bevyengine/bevy/pull/6773 comes to a conclusion.

**Comment by Milo123459** [comment]
yeah, also i presume some members of the bevy community are going to see the upstream issue and can hopefully help out to fix it upstream (in the rust repo.)
