### ISSUE TITLE
Migrate packet names to wiki.vg names

### ISSUE THREAD

**Issue by rj00a** [valence-rs/valence#56]
I've had a rule in place that the names of packets should match the names in [packets.json](https://github.com/valence-rs/valence/blob/main/extracted/packets.json). The reason for this was to make updating to new versions using the data extractor easier and to avoid potential legal issues because wiki.vg used the packet names from Mojang's mappings (this has mostly changed).

However, a lot of the yarn names are crap and it's way easier to just use wiki.vg. So we should transition all or most of the packet names to their names on wiki.vg for consistency.

Edit: This should be a gradual process so we don't cause too much pain right now.

**Comment by EmperialDev** [comment]
Can I take this one? (I'm very new to Git)

**Comment by TkTech** [comment]
> avoid potential legal issues

Just wanted to mention that some of those names were updated on the wiki _by_ Mojang employees, and they use the wiki internally. It would be very hard for them to argue infringement given both tacit (usage and contribution) and explicit (tweets, mentions) approval.

**Comment by rj00a** [comment]
> Just wanted to mention that some of those names were updated on the wiki by Mojang employees

Interesting! Had no idea Mojang used it themselves. But yea you're right.
