### ISSUE TITLE
Player hunger

### ISSUE THREAD

**Issue by SelfMadeSystem** [valence-rs/valence#565]
## Describe the problem related to your feature request.

Player hunger isn't implemented yet (food & saturation).

> Note: implementing when the player loses hunger isn't needed for this issue, only that they can.

## What solution would you like?

Implement the hunger manager & tell client about hunger updates.

## What alternative(s) have you considered?

Only implement the numbers ig idk

## Additional context

See [`net.minecraft.entity.player.HungerManager`](https://maven.fabricmc.net/docs/yarn-1.20.2+build.4/net/minecraft/entity/player/HungerManager.html) & [`HealthUpdateS2CPacket`](https://maven.fabricmc.net/docs/yarn-1.20.2+build.4/net/minecraft/network/packet/s2c/play/HealthUpdateS2CPacket.html)

**Comment by dyc3** [comment]
This sounds like implementing vanilla behavior, which is out of scope for valence. Is client behavior affected by this? In other words, does the client automatically update hunger and saturation without the server telling it to?

**Comment by SelfMadeSystem** [comment]
> This sounds like implementing vanilla behavior, which is out of scope for valence. Is client behavior affected by this? In other words, does the client automatically update hunger and saturation without the server telling it to?

The client does not automatically update hunger and saturation without the server telling it to, but there is also no way to tell the client about their own hunger right now either. In my opinion, I agree that implement behavior such as automatically decreasing food level when player runs, automatic regeneration, etc. is out of scope, but I also believe that just implement the basics so that it's usable by devs wouldn't be outside the scope.

If anything, from what I can tell, I would say that the current state of #558 is actually outside the scope of valence regarding implementing status effect behavior.

**Comment by dyc3** [comment]
"Vanilla behavior" is any behavior that is not client predicted. If something the client does would cause it to become out of sync with server state, valence needs to account for that so that it's capable of detecting it and correcting client state if desired by the user.

For example: the furnace crafting recipe is vanilla behavior, but the concept of a crafting recipe is not. Minecraft's terrain generation is vanilla behavior, but the concept of chunks is not.

So regarding potions, we only need to implement what's necessary to get the client to show the effect in the UI. We don't need to implement any of the actual effects unless the client makes state predictions that would invalidate the server's state.

**Comment by SelfMadeSystem** [comment]
> "Vanilla behavior" is any behavior that is not client predicted. If something the client does would cause it to become out of sync with server state, valence needs to account for that so that it's capable of detecting it and correcting client state if desired by the user.
> 
> For example: the furnace crafting recipe is vanilla behavior, but the concept of a crafting recipe is not. Minecraft's terrain generation is vanilla behavior, but the concept of chunks is not.
> 
> So regarding potions, we only need to implement what's necessary to get the client to show the effect in the UI. We don't need to implement any of the actual effects unless the client makes state predictions that would invalidate the server's state.
> 
> An exception we have is "would having this behavior or feature make it easier for end users without limiting anything", which is evaluated case by case, based entirely on opinion.

Alright, thanks for the clarification. I'll remove the potion stuff then and make it ready for merging then. I'll keep this issue open.
