### ISSUE TITLE
Update the `def_enum!` macro to be able to handle `Ident`s for values

### ISSUE THREAD

**Issue by dyc3** [valence-rs/valence#59]
Update the `def_enum!` macro to be able to handle strings for values, eg:
```rust
def_enum! {
        RecipeType: Ident {
            CraftingShapeless = "crafting_shapeless",
            CraftingShaped = "crafting_shaped",
            ...
        }
    }
```

Needed for creating the packet definitions for `UpdateRecipes` and `UpdateTags`.

**Comment by dyc3** [comment]
I was misunderstanding how the def_enum! macro worked. This actually works

**Comment by rj00a** [comment]
How needed is this? Don't think this is easy to do with #153 unfortunately.

**Comment by dyc3** [comment]
I've somewhat lost the context on this, but if I remember correctly I was having a bit of trouble creating packet definitions for those packets. The [Update Recipes packet](https://wiki.vg/Protocol#Update_Recipes) has a type field which holds an `Ident`, and it would be nice to be able to use an enum for that.

Probably not urgent.

**Comment by rj00a** [comment]
Alright, I'll go ahead and close this for now.
