### ISSUE TITLE
Ask if the developer can upload this on bilibili no. In China, we can't see this demo video through YouTube.

### ISSUE THREAD

**Issue by Inotart** [valence-rs/valence#630]
## Describe the problem related to your feature request.

 In China, we can't see this demo video through YouTube.

## What solution would you like?

Ask if the developer can upload this on bilibili no.

## What alternative(s) have you considered?

出国,但这不现实。中国有国家防火墙的存在,没有办法通过任何合法手段看演示视频

## Additional context
(Note: This is not due to the inaccessibility caused by my computer network.)
![image](https://github.com/valence-rs/valence/assets/101685021/7b49654c-bbba-4f79-b303-665f1caf24b5)

**Comment by Inotart** [comment]
Including Discord

**Comment by LiamTheNinja5** [comment]
https://protonvpn.com/free-vpn

**Comment by Inotart** [comment]
> https://protonvpn.com/free-vpn。
> 
> 开发人员将无法上传到 bilibili，因为他不在中国。

oh no,all right。But the vpn is not can use.

**Comment by Inotart** [comment]
> https://protonvpn.com/free-vpn。
> 
> 开发人员将无法上传到 bilibili，因为他不在中国。

<img width="346" alt="4706a27a46901f8c8c798cf8d4324c9f" src="https://github.com/valence-rs/valence/assets/101685021/bacc4acb-ced9-4676-8cee-eba890a4c8a0">

**Comment by AviiNL** [comment]
Sorry, but this is not really an issue with the valence code-base.
