### ISSUE TITLE
Session server could not verify username

### ISSUE THREAD

**Issue by Tenuka22** [valence-rs/valence#673]
How to fix this error, I'm in ultimc

**Comment by dyc3** [comment]
There's not enough info here to help you. Can you provide the text for the errors you are getting?

**Comment by LiamTheNinja5** [comment]
Quick question, are you using _ultimc_ or _Multimc_? because ultimc is unsupported because Valence does not support cracked clients as stated in the FAQ channel on the discord.

**Comment by Tenuka22** [comment]
I'm using poly mc
