### ISSUE TITLE
Cannot reach server from another host when config address function is not overwritten

### ISSUE THREAD

**Issue by dani162** [valence-rs/valence#77]
Currently we can not reach the server from another host if you not overwrite the ip address in the config.
I think we should document this behavior and maybe also change the default behavior to accept request from all interfaces (use address `0.0.0.0` instead of `localhost`).

https://github.com/valence-rs/valence/blob/00668839bdfa026b15e7b5b0dd1cabb3f16d25a3/src/config.rs#L52-L60

To override the address we currently have to implement following function:
```rust
impl Config for Game {
    ...
    fn address(&self) -> SocketAddr {
        SocketAddrV4::new(Ipv4Addr::new(0, 0, 0, 0), 25565).into()
    }
}
```
See also: https://stackoverflow.com/questions/42435723/rust-tcplistener-does-not-response-outside-request

I can create a pr tomorrow, if needed

**Comment by rj00a** [comment]
Yeah this sounds good. I wasn't aware `0.0.0.0` was a thing.
