### ISSUE TITLE
Refactor `Slot` so that it's easier to work with

### ISSUE THREAD

**Issue by dyc3** [valence-rs/valence#78]
Working with slots is somewhat cumbersome because sometimes you want to represent that the item is present no matter what. 

- [ ] Add a new type `ItemStack` with the fields that are in `Slot::Present`
- [ ] Change `Slot::Present { .. }` to `Slot::Present(ItemStack)`
- [ ] Implement `From<Slot> for Option<ItemStack>` and vice versa

OR, alternatively we could do this instead:
- [ ] Get rid of slot and just use `Option<ItemStack>`

**Comment by rj00a** [comment]
Yeah this is good. Maybe extracted item data and the `ItemStack` type can go in `item.rs` at the root and then `Slot` can be internal to the protocol module.
