### ISSUE TITLE
Mojang session server unhandled response format

### ISSUE THREAD

**Issue by TerminatorNL** [valence-rs/valence#95]
When logging into a valence server, sometimes the log-in process fails with the following error message:
`[2022-09-30T13:13:11Z ERROR valence::server] connection to 127.0.0.1:33980 ended: error during login: EOF while parsing a value at line 1 column 0`

This is quite hard to reproduce, but I had the most success of reproducing this error when: 
1. Log into the server
2. Disconnect
3. Log back in after about 10 minutes.

This is not guaranteed to work, however.

I went through the log-in process and located the origin of this error to be the following line:
https://github.com/valence-rs/valence/blob/838a75d2f94f0a2aa212f97593623a4ef3ea3b6d/src/server.rs#L725

The `json()` call reads the bytes in the body that is sent back to valence from the Mojang session server.

Under normal circumstances, the Mojang session server return status `200` but in this case it returns status code `204`. Furthermore, the Mojang session server does not transmit any content despite sending `"content-type": "application/json"` in the header fields. This means that when the `json()` tries to read the bytes in the body, it ends up reading zero bytes and throws an EOF error. (response body = 0 bytes) 

I have added the headers and some additional details below (using `format!("{:?}", response)`):
```
Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("sessionserver.mojang.com")), port: None, path: "/session/minecraft/hasJoined", query: Some("username=Terminator_NL&serverId=**redacted**&ip=127.0.0.1"), fragment: None }, status: 204, headers: {"cache-control": "no-store", "content-type": "application/json", "x-minecraft-request-id": "859782bb07ebb57b", "x-cache": "CONFIG_NOCACHE", "x-azure-ref": "0Z+s2YwAAAABo/fb1SCwJQZ55W2ymkslNQU1TMDRFREdFMTgxNQBhODc2NTI0My1lMjE0LTQ4NmEtYmFiNC04NDAwMWI0MDA5YzY=", "set-cookie": "ASLBSA=0003af36d910048a208f98008a8d9254c59859f96a40a025a2738de7c22fb2e6c983; path=/; secure", "set-cookie": "ASLBSACORS=0003af36d910048a208f98008a8d9254c59859f96a40a025a2738de7c22fb2e6c983; samesite=none; path=/; secure", "date": "Fri, 30 Sep 2022 13:13:11 GMT"} }
```

**SPECULATION**
I am not sure what status code 204 is, or how to handle it. I can only assume that 204 means "It's still valid, just use my previous response" and Mojang expects the minecraft server to cache the authentication responses.

**Comment by rj00a** [comment]
Assuming your speculation is correct, I can think of a few questions that must be answered before a solution can be implemented:
- How long must player data be held in the cache before we can safely remove it?
- Must the cache be saved to disk or can it be saved in-memory? If it can be done in-memory then we can completely hide that logic from users. If it must persist to disk then we would need to make some kind of API for it.

I suspect that saving to disk is necessary because the session server has no way of knowing when the server goes online/offline.

**Comment by TerminatorNL** [comment]
Investigation update:

Documentation on this topic is severely lacking, but [this bug report](https://bugs.mojang.com/browse/MC-253237) might provide some input.

I'll quote:
>[[Mojang] Petter Gisslen](https://bugs.mojang.com/secure/ViewProfile.jspa?name=pgisslen) added a comment - [23/Jun/22 10:33 AM](https://bugs.mojang.com/browse/MC-253237?focusedCommentId=1176461&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1176461)
>
>Hi
> We have enabled ip validation quite recently. This means that if the server has IP validation turned on(only a 5-10% of public server has) it will provide the public IP of the connecting client in the hasJoined request and the sessionserver will compare it with the public IP of the Join request. It the IP's does not match, we reject the hasJoined request (204)
> 
> If public IP och both server and client are the same we consider it on the same LAN and accept that also.


It looks like the 204 status code is a way for the server to prevent minecraft clients joining through a proxy. `prevent-proxy-connections`

When `prevent-proxy-connections` is true, the vanilla Minecraft server will include the client ip address in the request.
See: `com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService#hasJoinedServer`
```java
        if (address != null) {
            arguments.put("ip", address.getHostAddress());
        }
```

It looks like Valence includes the IP in every request, and therefore implies that we want to prevent proxy connections
https://github.com/valence-rs/valence/blob/838a75d2f94f0a2aa212f97593623a4ef3ea3b6d/src/config.rs#L228

This means that my speculation was wrong (huzzah!) and we have something to work with now...

**Comment by TerminatorNL** [comment]
I can reliably reproduce this bug by editing setting the IP to something other than my own in https://github.com/valence-rs/valence/blob/838a75d2f94f0a2aa212f97593623a4ef3ea3b6d/src/config.rs#L228

In this case we should return a "Failed to verify username" (multiplayer.disconnect.unverified_username) error, I can start writing a pull for this :+1:

**Comment by rj00a** [comment]
Nice work!
